local winbar = require("codex_workbench.ui.review.winbar")
local output_winbar = require("codex_workbench.ui.output_winbar")

describe("winbar", function()
  after_each(function()
    winbar.clear()
  end)

  it("renders review key hints", function()
    local win = vim.api.nvim_get_current_win()
    winbar.apply(win, { kind = "review_tree" }, true)
    local rendered = winbar.render()
    assert.is_true(rendered:find("[a]", 1, true) ~= nil)
    assert.is_true(rendered:find("]f", 1, true) ~= nil)
    assert.is_true(rendered:find("[q]", 1, true) ~= nil)
  end)

  it("clears the window option when disabled", function()
    local win = vim.api.nvim_get_current_win()
    winbar.apply(win, { kind = "review_tree" }, true)
    winbar.apply(win, { kind = "review_tree" }, false)
    assert.equals("", vim.wo[win].winbar)
  end)

  it("renders compact review hints below 80 columns", function()
    local rendered = winbar.render_context({ kind = "review_tree" }, nil, 60)
    assert.is_true(rendered:find("next%-file") ~= nil)
    assert.is_true(rendered:find("accept%-all") == nil)
  end)

  it("renders output phase and elapsed status", function()
    local rendered = output_winbar.render({ width = 100, phase = "streaming", started_at = os.time() - 12 })
    assert.is_true(rendered:find("Codex Output", 1, true) ~= nil)
    assert.is_true(rendered:find("phase: streaming", 1, true) ~= nil)
    assert.is_true(rendered:find("elapsed", 1, true) ~= nil)
  end)
end)
